# Generated by Django 3.1.4 on 2020-12-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("show_at_home", models.BooleanField(default=True, verbose_name="Show at home")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["order"],},
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128, verbose_name="Title")),
                ("text", models.TextField(verbose_name="Text")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="requirement.category", verbose_name="Category"
                    ),
                ),
            ],
            options={"ordering": ["order"],},
        ),
    ]
