# Generated by Django 3.1.4 on 2020-12-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requirement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128, verbose_name="Title")),
                ("text", models.TextField(verbose_name="Text")),
            ],
        ),
        migrations.AddField(
            model_name="requirement",
            name="test_cases",
            field=models.ManyToManyField(to="requirement.TestCase", verbose_name="Test cases"),
        ),
    ]
