# Generated by Django 3.1.4 on 2020-12-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requirement", "0007_auto_20201224_1051"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="summary",
            field=models.TextField(default="", max_length=256, verbose_name="Summary"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="summary_en",
            field=models.TextField(max_length=256, null=True, verbose_name="Summary"),
        ),
        migrations.AddField(
            model_name="category",
            name="summary_ru",
            field=models.TextField(max_length=256, null=True, verbose_name="Summary"),
        ),
    ]
