# Generated by Django 3.1.4 on 2020-12-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requirement", "0008_auto_20201224_1053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="summary",
            field=models.TextField(help_text="Hint at left panel", max_length=256, verbose_name="Summary"),
        ),
        migrations.AlterField(
            model_name="category",
            name="summary_en",
            field=models.TextField(help_text="Hint at left panel", max_length=256, null=True, verbose_name="Summary"),
        ),
        migrations.AlterField(
            model_name="category",
            name="summary_ru",
            field=models.TextField(help_text="Hint at left panel", max_length=256, null=True, verbose_name="Summary"),
        ),
    ]
