# Generated by Django 3.1.4 on 2020-12-24 13:35

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("requirement", "0009_auto_20201224_1053"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportRequest",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="For downloading", unique=True, verbose_name="Unique ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Created"), ("finished", "Finished"), ("failed", "Failed")],
                        default="created",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="exports", verbose_name="File")),
                ("data", models.JSONField(verbose_name="Export data")),
                ("created", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created")),
                ("finished", models.DateTimeField(blank=True, null=True, verbose_name="Finished")),
            ],
            options={"ordering": ["created"],},
        ),
    ]
