# Generated by Django 3.1.4 on 2020-12-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requirement", "0010_exportrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportrequest",
            name="language",
            field=models.CharField(
                choices=[("ru", "Russian"), ("en", "English")], default="en", max_length=6, verbose_name="Language"
            ),
        ),
    ]
