# Generated by Django 3.1.4 on 2020-12-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("requirement", "0011_exportrequest_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["order"], "verbose_name": "category", "verbose_name_plural": "Categories"},
        ),
    ]
