# Generated by Django 3.1.4 on 2021-01-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requirement", "0012_auto_20201225_2049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("started", "Started"),
                    ("finished", "Finished"),
                    ("failed", "Failed"),
                ],
                default="created",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
