# Generated by Django 3.1.4 on 2021-01-03 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0013_auto_20210102_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportrequest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='category',
        ),
        migrations.AddField(
            model_name='requirement',
            name='categories',
            field=models.ManyToManyField(to='requirement.Category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='exportrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='For downloading', primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
