# Generated by Django 3.1.4 on 2021-01-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0014_auto_20210103_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='summary',
            field=models.TextField(help_text='Hint at left panel', max_length=1024, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='category',
            name='summary_en',
            field=models.TextField(help_text='Hint at left panel', max_length=1024, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='category',
            name='summary_ru',
            field=models.TextField(help_text='Hint at left panel', max_length=1024, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='summary',
            field=models.TextField(max_length=1024, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='summary_en',
            field=models.TextField(max_length=1024, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='summary_ru',
            field=models.TextField(max_length=1024, null=True, verbose_name='Summary'),
        ),
    ]
