# Generated by Django 3.1.4 on 2021-07-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0015_auto_20210105_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default category'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default requirement'),
        ),
    ]
