# Generated by Django 3.1.4 on 2020-12-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("seo_description", models.CharField(default="", max_length=255, verbose_name="Description")),
                ("seo_title_base", models.CharField(default="", max_length=64, verbose_name="Title (base part)")),
            ],
            options={"verbose_name": "Site config",},
        ),
    ]
