# Generated by Django 3.1.4 on 2020-12-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="config", name="seo_description",),
        migrations.RemoveField(model_name="config", name="seo_title_base",),
        migrations.AddField(
            model_name="config",
            name="export_company_name",
            field=models.CharField(default="", max_length=256, verbose_name="Title"),
            preserve_default=False,
        ),
    ]
