# Generated by Django 3.1.4 on 2020-12-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_auto_20201225_2049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="export_company_name",
            field=models.CharField(max_length=256, verbose_name="Company name"),
        ),
    ]
