# Generated by Django 3.1.4 on 2021-07-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210102_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_value', models.CharField(default='Security assessment', max_length=256, verbose_name='Button value')),
                ('button_link', models.CharField(default='https://whitespots.io/security-assessment', max_length=256, verbose_name='Button link')),
            ],
            options={
                'verbose_name': 'Assessment Button',
            },
        ),
    ]
